### ISSUE TITLE
If redirect to QBO Connector automatic after auth?

### ISSUE THREAD

**Issue by Ignorant-lxf** [rwestlund/quickbooks-go#19]
Hi,I have some questions.

How can I redirect to QBO Connector after  have authorization?
@lukecyca  @nsotgui  @rwestlund

**Comment by rwestlund** [comment]
If you're talking about QuickBooks Web Connector, that's for desktop versions of QB. This library is only for the online version.

If you're talking about deep linking to something within QBO like an invoice, it's like this:
```
<a href="https://${sandbox_mode ? 'c50.sandbox.':''}qbo.intuit.com/app/invoice?txnId=${quickbooks_id}">link</a>
```
